[package]
name = "quarky"
version = "0.0.2"
authors = ["adumbidiot <nathaniel.daniel23@outlook.com>"]
edition = "2018"
publish = false

[dependencies]
serenity = { version = "0.6.3", features = [ "voice" ] }
rand = "0.7.0"
serde_json = "1.0.40"
clokwerk = "0.2.2"
toml = "0.5.3"
serde = { version = "1.0.99", features = [ "derive" ] }
tokio = "0.1.22"
parking_lot = "0.9.0"
lazy_static = "1.3.0"
indexmap = "1.1.0"
zalgo = { git = "https://github.com/adumbidiot/zalgo-rs", rev = "1772ba1d8a0769093f84207ea2e797eacd597629" }

# Local
reddit = { path = "./lib/reddit" }

[workspace]
members = [ "lib/reddit" ]

#[profile.release]
#lto = true
#codegen-units = 1
#debug = false
#opt-level = 3
#debug-assertions = false