[package]
name = "quarky"
version = "0.0.2"
authors = [ "adumbidiot <nathaniel.daniel23@outlook.com>" ]
edition = "2018"
publish = false

[dependencies]
clokwerk = "0.3.3"
http = "0.2.1"
indexmap = "1.6.0"
lazy_static = "1.4.0"
rand = "0.7.3"
reddit = { git = "https://github.com/adumbidiot/reddit-rs", rev = "2451ce9" }
serde = { version = "1.0.115", features = [ "derive" ] }
serde_json = "1.0.58"
serenity = { version = "0.8.6", features = [ "voice" ] }
tokio = { version = "0.2.22", features = [ "rt-threaded" ] }
toml = "0.5.6"
zalgo = { git = "https://github.com/adumbidiot/zalgo-rs", rev = "e630ea0" }

[patch.crates-io]
# Tracking PR for adding async to serenity
serenity = { git = "https://github.com/Lakelezz/serenity", rev = "a2e8cde" }

#[profile.release]
#lto = true
#codegen-units = 1
#debug = false
#opt-level = 3
#debug-assertions = false