[package]
name = "quarky"
version = "0.0.2"
authors = [ "adumbidiot <nathaniel.daniel23@outlook.com>" ]
edition = "2018"
publish = false

[dependencies]
clokwerk = "0.3.4"
chrono = "0.4.19"
egg-mode = "0.15.0"
fern = { version = "0.6.0", features = [ "colored" ] }
http = "0.2.2"
indexmap = "1.6.1"
lazy_static = "1.4.0"
log = "0.4.14"
rand = "0.7.3"
reddit = { git = "https://github.com/adumbidiot/reddit-rs", rev = "f7c7b398e52a141389d1523fc6525f0f8728b501" }
serde = { version = "1.0.123", features = [ "derive" ] }
serde_json = "1.0.62"
serenity = { version = "0.9.3", features = [ "voice" ] }
thiserror = "1.0.23"
tokio = { version = "0.2.25", features = [ "rt-threaded" ] }
toml = "0.5.8"
zalgo = { git = "https://github.com/adumbidiot/zalgo-rs", rev = "e630ea0" }

# [profile.release]
# lto = true
# codegen-units = 1
# debug = false
# opt-level = 3
# debug-assertions = false