[package]
name = "quarky"
version = "0.0.1"
authors = ["adumbidiot <nathaniel.daniel23@outlook.com>"]
edition = "2018"
publish = false

[dependencies]
serenity = "0.6"
rand = "0.7"
serde_json = "1"
clokwerk = "0.2"
toml = "0.5"
serde = { version = "1", features = [ "derive" ] }

[profile.release]
lto = true
codegen-units = 1
debug = false
opt-level = 3
debug-assertions = false