[package]
name = "quarky"
version = "0.0.2"
authors = [ "adumbidiot <nathaniel.daniel23@outlook.com>" ]
edition = "2018"
publish = false

[dependencies]
clokwerk = "0.3.5"
chrono = "0.4.19"
egg-mode = "0.15.0"
fern = { version = "0.6.0", features = [ "colored" ] }
http = "0.2.4"
indexmap = "1.6.2"
lazy_static = "1.4.0"
log = "0.4.14"
rand = "0.8.3"
reddit = { git = "https://github.com/adumbidiot/reddit-rs", rev = "39257920c3a7eaaffc88407f36f498bffc397a5a" }
serde = { version = "1.0.125", features = [ "derive" ] }
serde_json = "1.0.64"
serenity = { version = "0.10.5", features = [ "voice" ] }
songbird = "0.1.6"
thiserror = "1.0.24"
tokio = { version = "1.6.1", features = [ "rt-multi-thread", "signal" ] }
toml = "0.5.8"
zalgo = { git = "https://github.com/adumbidiot/zalgo-rs", rev = "e630ea0" }

# [profile.release]
# lto = true
# codegen-units = 1
# debug = false
# opt-level = 3
# debug-assertions = false

[patch.crates-io]
# Tokio 1.0 Support
egg-mode = { git = "https://github.com/egg-mode-rs/egg-mode", rev = "6b81073eba9c3b123ca0e80bdb5ef61d1758f131" }
