[package]
name = "quarky"
version = "0.0.2"
authors = [ "adumbidiot <nathaniel.daniel23@outlook.com>" ]
edition = "2021"
publish = false

[dependencies]
clokwerk = "0.3.5"
chrono = "0.4.19"
egg-mode = "0.16.0"
fern = { version = "0.6.1", features = [ "colored" ] }
http = "0.2.7"
indexmap = "1.8.1"
lazy_static = "1.4.0"
log = "0.4.17"
rand = "0.8.5"
reddit = { git = "https://github.com/adumbidiot/reddit-rs" }
serde = { version = "1.0.137", features = [ "derive" ] }
serde_json = "1.0.81"
serenity = { git = "https://github.com/serenity-rs/serenity", branch = "next" }
songbird = "0.2.2"
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = [ "rt-multi-thread", "signal" ] }
toml = "0.5.9"
zalgo = { git = "https://github.com/adumbidiot/zalgo-rs" }

[profile.release]
lto = "fat"
codegen-units = 1
debug = false
opt-level = 3
debug-assertions = false

[patch.crates-io]
# # Support for cross-compiling, like msvc -> mingw
# songbird = { git = "https://github.com/adumbidiot/songbird", branch = "audiopus-0.3.0" }

# Updated songbird + support for cross-compiling, like msvc -> mingw
songbird = { git = "https://github.com/FelixMcFelix/songbird", branch = "symphonia" }

[package.metadata.rpi-deploy]
targets = [
    "armv7-unknown-linux-gnueabihf",
]
