[package]
name = "quarky"
version = "0.1.0"
authors = ["adumbidiot <nathaniel.daniel23@outlook.com>"]
edition = "2018"

[dependencies]
serenity = "0.5"
rand = "0.5"
serde_json = "1"
clokwerk = "0.1"
toml = "0.4"
serde_derive = "1.0"
serde = "1"