[package]
name = "quarky"
version = "0.1.0"
authors = ["adumbidiot <nathaniel.daniel23@outlook.com>"]
edition = "2018"

[dependencies]
serenity = "0.6"
rand = "0.7"
serde_json = "1"
clokwerk = "0.2"
toml = "0.5"
serde = { version = "1", features = [ "derive" ] }