[package]
name = "quarky"
version = "0.0.2"
authors = [ "adumbidiot <nathaniel.daniel23@outlook.com>" ]
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.57"
camino = { version = "1.0.9", features = [ "serde1" ] }
clokwerk = "0.3.5"
chrono = "0.4.19"
egg-mode = { version = "0.16.0", default-features = false, features = [ "rustls" ] }
fern = { version = "0.6.1", features = [ "colored" ] }
http = "0.2.7"
indexmap = "1.8.2"
lazy_static = "1.4.0"
log = "0.4.17"
rand = "0.8.5"
reddit = { git = "https://github.com/adumbidiot/reddit-rs" }
serde = { version = "1.0.137", features = [ "derive" ] }
serde_json = "1.0.81"
serenity = { version = "0.11" }
songbird = "0.3.0"
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = [ "rt-multi-thread", "signal" ] }
toml = "0.5.9"
zalgo = { git = "https://github.com/adumbidiot/zalgo-rs" }
argh = "0.1.7"

[profile.release]
lto = "fat"
codegen-units = 1
debug = false
opt-level = 3
debug-assertions = false
strip = "symbols"

[patch.crates-io]

[package.metadata.deb]
name = "quarky"
depends = ""
assets = [
    [ "target/release/quarky", "usr/bin/", "700" ],
    [ "deb-config.toml", "etc/quarky/config.toml", "600" ],
]
conf-files = [
    "etc/quarky/config.toml",
]
maintainer-scripts = "debian/"

[package.metadata.deb.systemd-units]
enable = true
start = true

[package.metadata.rpi-deploy]
targets = [
    "armv7-unknown-linux-gnueabihf",
    "aarch64-unknown-linux-gnu",
]
