[package]
name = "quarky"
version = "0.0.2"
authors = [ "adumbidiot <nathaniel.daniel23@outlook.com>" ]
edition = "2018"
publish = false

[dependencies]
clokwerk = "0.2.2"
indexmap = "1.3.0"
lazy_static = "1.4.0"
parking_lot = "0.9.0"
rand = "0.7.3"
serde = { version = "1.0.102", features = [ "derive" ] }
serde_json = "1.0.41"
serenity = { version = "0.8.6", features = [ "voice" ] }
tokio = "0.1.22"
toml = "0.5.5"
zalgo = { git = "https://github.com/adumbidiot/zalgo-rs", rev = "e630ea0" }

# Local
reddit = { path = "./lib/reddit" }

[workspace]
members = [ "lib/reddit" ]

#[profile.release]
#lto = true
#codegen-units = 1
#debug = false
#opt-level = 3
#debug-assertions = false