[package]
name = "quarky"
version = "0.0.2"
authors = [ "adumbidiot <nathaniel.daniel23@outlook.com>" ]
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.71"
camino = { version = "1.1.4", features = [ "serde1" ] }
# clokwerk = "0.4.0"
clokwerk = { git = "https://github.com/mdsherry/clokwerk" }
chrono = { version = "0.4.24", default-features = false }
fern = { version = "0.6.2", features = [ "colored" ] }
http = "0.2.9"
indexmap = "1.9.3"
lazy_static = "1.4.0"
log = "0.4.19"
rand = "0.8.5"
reddit = { git = "https://github.com/adumbidiot/reddit-rs", default-features = false, features = [ "rustls-tls" ] }
serde = { version = "1.0.163", features = [ "derive" ] }
serde_json = "1.0.96"
serenity = "0.11.5"
songbird = "0.3.2"
thiserror = "1.0.40"
tokio = { version = "1.28.1", features = [ "rt-multi-thread", "signal" ] }
toml = "0.7.3"
zalgo = { git = "https://github.com/adumbidiot/zalgo-rs" }
argh = "0.1.10"
twitter-scraper = { path = "lib/twitter-scraper", default-features = false, features = [ "rustls-tls" ] }

[profile.release]
lto = "fat"
codegen-units = 1
debug = false
opt-level = 3
debug-assertions = false
strip = "symbols"

[patch.crates-io]

[workspace]
members = [
    "lib/*"
]

[package.metadata.deb]
name = "quarky"
depends = ""
assets = [
    [ "target/release/quarky", "usr/bin/", "700" ],
    [ "deb-config.toml", "etc/quarky/config.toml", "600" ],
]
conf-files = [
    "etc/quarky/config.toml",
]
maintainer-scripts = "debian/"

[package.metadata.deb.systemd-units]
enable = true
start = true

[package.metadata.rpi-deploy]
targets = [
    "armv7-unknown-linux-gnueabihf",
    "aarch64-unknown-linux-gnu",
]