[package]
name = "quarky"
version = "0.0.2"
authors = ["adumbidiot <nathaniel.daniel23@outlook.com>"]
edition = "2018"
publish = false

[dependencies]
serenity = "0.6"
rand = "0.7"
serde_json = "1.0"
clokwerk = "0.2"
toml = "0.5"
serde = { version = "1.0", features = [ "derive" ] }
tokio = "0.1"
parking_lot = "0.9"
lazy_static = "1.3"
indexmap = "1.1"
zalgo = { git = "https://github.com/adumbidiot/zalgo-rs", rev = "1772ba1d8a0769093f84207ea2e797eacd597629" }

# Local
reddit = { path = "./lib/reddit" }

[workspace]
members = [ "lib/reddit" ]

#[profile.release]
#lto = true
#codegen-units = 1
#debug = false
#opt-level = 3
#debug-assertions = false