# Fill out this field with your token
# token = "[TOKEN]"

# Put your desired bot prefix here
prefix = "~" 

[twitter]
# Put your bearer token here
# bearer_token = "[BEARER_TOKEN]"

# The log config
[log]
# The log file destination
log-file = "/var/log/quarky.log"