targets = [
	{ triple = "x86_64-unknown-linux-gnu" },
	{ triple = "x86_64-unknown-linux-musl" },
	{ triple = "x86_64-apple-darwin" },
	{ triple = "x86_64-pc-windows-msvc" },
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
ignore = []

[licenses]
unlicensed = "deny"
copyleft = "warn"
confidence-threshold = 0.93
default = "deny"
private = { ignore = true }
allow = [ "Apache-2.0", "MIT", "ISC", "Zlib", "BSD-3-Clause", "MPL-2.0", "Unicode-DFS-2016" ]
exceptions = [
    { name = "ring", allow = [ "MIT", "ISC", "OpenSSL" ] },
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]

[bans]
multiple-versions = "warn"
highlight = "all"
skip = [	        
    # Blocked on `crossbeam-utils` bumping `cfg-if` to `1.0.x`
    { name = "cfg-if", version = "1.0.0" },
    
    # Blocked on serenity updating "syn"
    { name = "syn", version = "1.0.109" },
    
    { name = "bitflags", version = "1.3.2" },
]

# Mostly soundness denies since the advisory lacks a section for soundess bugs
deny = [                
    # Appears to be moving towards integrating rio more tightly for io_uring support
    { name = "sled", version = "*" },
    
    # The general idea seems unsound, and the current version does contain UB.
    # https://github.com/Kimundi/owning-ref-rs/issues/71
    { name = "owning_ref", version = "*" },
    
    # It's a crate only intended for testing; people insist on using it for some reason.
    # https://crates.io/crates/markup5ever_rcdom/0.1.0
    { name = "markup5ever_rcdom", version = "0.1.0" },
    
    # https://github.com/RustSec/advisory-db/issues/826
    { name = "totally-safe-transmute", version = "*" },
    
    # https://github.com/RustSec/advisory-db/issues/743
    { name = "fast-floats", version = "*" },
    
    # https://github.com/RustSec/advisory-db/issues/913
    { name = "hexchat", version = ">=0.3.0" },
]

[sources]
unknown-registry = "warn"
unknown-git = "deny"
allow-git = [
    "https://github.com/mdsherry/clokwerk",
]

[sources.allow-org]
github = [
    "adumbidiot",
]