targets = [
	{ triple = "x86_64-unknown-linux-gnu" },
	{ triple = "x86_64-unknown-linux-musl" },
	{ triple = "x86_64-apple-darwin" },
	{ triple = "x86_64-pc-windows-msvc" },
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
ignore = []

[licenses]
unlicensed = "deny"
copyleft = "warn"
confidence-threshold = 0.93
default = "deny"
private = { ignore = true }
allow = [ "Apache-2.0", "MIT", "ISC", "Zlib", "BSD-3-Clause", "MPL-2.0" ]
exceptions = [
    { name = "ring", allow = [ "MIT", "ISC", "OpenSSL" ] },
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]

[bans]
multiple-versions = "warn"
highlight = "all"
skip = [	        
    # Blocked on `crossbeam-utils` bumping `cfg-if` to `1.0.x`
    { name = "cfg-if", version = "1.0.0" },
    
    # Blocked on `serenity` updating `async-tungstenite` to `0.13.x`
    { name = "webpki-roots", version = "0.20.0" },
    { name = "tungstenite", version = "0.11.1" },
    { name = "bytes", version = "0.5.6" },
    { name = "async-tungstenite", version = "0.11.0" },
    # { name = "base64", version = "0.12.3" },
    
    # Blocked on `pnet` removing `syntex`
    { name = "input_buffer", version = "0.3.1" },
    
    # Blocked on `tungstenite` and `zalgo` updating `rand` to `0.8.x`
    { name = "rand_core", version = "0.5.1" },
    { name = "rand_chacha", version = "0.2.2" },
    { name = "rand", version = "0.7.3" },
    { name = "getrandom", version = "0.1.16" },
    
    # Blocked on `enum-primitive` updating `num-traits` to `0.2.x`
    { name = "num-traits", version = "0.1.43" },
]

[sources]
unknown-registry = "warn"
unknown-git = "deny"
allow-git = [
	"https://github.com/adumbidiot/zalgo-rs",
	"https://github.com/adumbidiot/reddit-rs",
    "https://github.com/egg-mode-rs/egg-mode",
]