[package]
name = "rss-client"
version = "0.0.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
quick-xml = { version = "0.42.0", features = [ "serialize" ] }
reqwest = { version = "0.13.4", features = [], default-features = false }
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = [ "rt" ] }
url = { version = "2.5.8", features = ["serde"] }

[dev-dependencies]
tokio = { version = "1.53.1", features = [ "macros" ] }

[features]
default = [
    "rustls",
]

native-tls = [
    "reqwest/native-tls",
]

rustls = [
    "reqwest/rustls",
]
