name: CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-lint-cargo-${{ hashFiles('**/Cargo.lock') }}
        
      - name: Install Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
        
      - name: Check Fmt
        run: cargo fmt --all -- --check --color always
        
      - name: Check Clippy
        run: cargo clippy --tests --all -- -D warnings
        
  deny:
    name: Deny
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Deny
        uses: EmbarkStudios/cargo-deny-action@v2
        
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-build-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Install Toolchain
        uses: dtolnay/rust-toolchain@nightly
      
      - name: Build
        run: cargo build --all --verbose
        
      - name: Tests
        run: cargo test --all --verbose